export const GET_FLIGHT_RESULTS = 'GET_FLIGHT_RESULTS';
export const RESET_FLIGHT_RESULTS = 'RESET_FLIGHT_RESULTS';
export const SELECT_FLIGHT_TICKET = 'SELECT_FLIGHT_TICKET';
export const SET_DEPART_CITY = 'SET_DEPART_CITY';
export const SET_ARRIVAL_CITY = 'SET_ARRIVAL_CITY';
export const SET_DEPARTURE_DATE = 'SET_DEPARTURE_DATE';
export const SET_RETURN_DATE = 'SET_RETURN_DATE';
